source 'https://rubygems.org'
gem 'rails', '4.0.2'
gem 'pg'
gem 'sass-rails', '~> 4.0.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.0.0'
gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 1.2'
gem 'redcarpet'
gem 'coderay'
gem 'foundation-rails'
gem 'devise'
gem 'faker'
gem 'debugger'
gem 'simple_form'
gem 'font-awesome-rails'

group :test do
	gem 'rspec-rails'
	gem 'capybara'
	gem 'factory_girl_rails'
	gem 'simplecov'
end
